/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSectionsRouteImport } from './routes/_authenticated/sections'
import { Route as AuthenticatedVisualizationRouteImport } from './routes/_authenticated/visualization'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSectionsRoute = AuthenticatedSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisualizationRoute =
  AuthenticatedVisualizationRouteImport.update({
    id: '/visualization',
    path: '/visualization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/design': typeof AuthenticatedDesignRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/visualization': typeof AuthenticatedVisualizationRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/design': typeof AuthenticatedDesignRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sections': typeof AuthenticatedSectionsRoute
  '/visualization': typeof AuthenticatedVisualizationRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sections': typeof AuthenticatedSectionsRoute
  '/_authenticated/visualization': typeof AuthenticatedVisualizationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analysis'
    | '/design'
    | '/reports'
    | '/sections'
    | '/visualization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analysis'
    | '/design'
    | '/reports'
    | '/sections'
    | '/visualization'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analysis'
    | '/_authenticated/design'
    | '/_authenticated/reports'
    | '/_authenticated/sections'
    | '/_authenticated/visualization'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sections': {
      id: '/_authenticated/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AuthenticatedSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visualization': {
      id: '/_authenticated/visualization'
      path: '/visualization'
      fullPath: '/visualization'
      preLoaderRoute: typeof AuthenticatedVisualizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSectionsRoute: typeof AuthenticatedSectionsRoute
  AuthenticatedVisualizationRoute: typeof AuthenticatedVisualizationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSectionsRoute: AuthenticatedSectionsRoute,
  AuthenticatedVisualizationRoute: AuthenticatedVisualizationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
